SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE website;
TRUNCATE TABLE address;
TRUNCATE TABLE email;
TRUNCATE TABLE messaging;
TRUNCATE TABLE phone;

TRUNCATE TABLE circle_contact;

TRUNCATE TABLE contact;

TRUNCATE TABLE circle;

TRUNCATE TABLE `type`;


TRUNCATE TABLE civility;


TRUNCATE TABLE `user`;
TRUNCATE TABLE `role`;

SET FOREIGN_KEY_CHECKS = 1;
